In [1]:

import pandas as pd

In [2]:
data=pd.read_csv("D:\\Downloads\\bank.csv",sep=';')

In [3]:
data.shape

(4521, 17)

In [4]:
data.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
y            False
dtype: bool

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
age          4521 non-null int64
job          4521 non-null object
marital      4521 non-null object
education    4521 non-null object
default      4521 non-null object
balance      4521 non-null int64
housing      4521 non-null object
loan         4521 non-null object
contact      4521 non-null object
day          4521 non-null int64
month        4521 non-null object
duration     4521 non-null int64
campaign     4521 non-null int64
pdays        4521 non-null int64
previous     4521 non-null int64
poutcome     4521 non-null object
y            4521 non-null object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB


In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le=LabelEncoder()

In [8]:
le.fit(data.job)

LabelEncoder()

In [9]:
le.transform(data.job)

array([10,  7,  4, ...,  9,  1,  2])

In [10]:
data.job=le.transform(data.job)

In [11]:
data.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [12]:
data[['education','marital','job']]

education  marital  job
0       primary  married   10
1     secondary  married    7
2      tertiary   single    4
3      tertiary  married    4
4     secondary  married    1
...         ...      ...  ...
4516  secondary  married    7
4517   tertiary  married    6
4518  secondary  married    9
4519  secondary  married    1
4520   tertiary   single    2

[4521 rows x 3 columns]

In [14]:
data.education=le.fit_transform(data.education)

In [15]:
data.marital=le.fit_transform(data.marital)

In [16]:
data.housing=le.fit_transform(data.housing)

In [17]:
data.loan=le.fit_transform(data.loan)

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x=data[['age','job','marital','education','balance','housing','loan','duration','campaign','pdays','previous']]

In [20]:
y=data['y']

In [21]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2)

In [22]:
from sklearn.linear_model  import LogisticRegression

In [23]:
model=LogisticRegression()

In [24]:
model.fit(train_x,train_y)

C:\Users\Manirathinam\Anaconda3\Anaconda New\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
data['marital'].unique()

array([1, 2, 0], dtype=int64)

In [26]:
y_pred=model.predict(test_x)

In [27]:
pd.DataFrame({'actual':test_y,'predicted':y_pred})

actual predicted
1850     no        no
2288     no        no
2030     no        no
548      no        no
3939     no        no
...     ...       ...
1576     no        no
3128     no        no
3971     no        no
4219     no        no
2516     no        no

[905 rows x 2 columns]

In [28]:
import pandas as pd

In [29]:
data=pd.read_csv("D:\\Downloads\\bank.csv",sep=';')

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
age          4521 non-null int64
job          4521 non-null object
marital      4521 non-null object
education    4521 non-null object
default      4521 non-null object
balance      4521 non-null int64
housing      4521 non-null object
loan         4521 non-null object
contact      4521 non-null object
day          4521 non-null int64
month        4521 non-null object
duration     4521 non-null int64
campaign     4521 non-null int64
pdays        4521 non-null int64
previous     4521 non-null int64
poutcome     4521 non-null object
y            4521 non-null object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB


In [31]:
pd.get_dummies(data[['marital','job','education','default','housing','loan','contact','poutcome']])

marital_divorced  marital_married  marital_single  job_admin.  \
0                    0                1               0           0   
1                    0                1               0           0   
2                    0                0               1           0   
3                    0                1               0           0   
4                    0                1               0           0   
...                ...              ...             ...         ...   
4516                 0                1               0           0   
4517                 0                1               0           0   
4518                 0                1               0           0   
4519                 0                1               0           0   
4520                 0                0               1           0   

      job_blue-collar  job_entrepreneur  job_housemaid  job_management  \
0                   0                 0              0               0   
1                   0                 0              0               0   
2                   0                 0              0               1   
3                   0                 0              0               1   
4                   1                 0              0               0   
...               ...               ...            ...             ...   
4516                0                 0              0               0   
4517                0                 0              0               0   
4518                0                 0              0               0   
4519                1                 0              0               0   
4520                0                 1              0               0   

      job_retired  job_self-employed  ...  housing_yes  loan_no  loan_yes  \
0               0                  0  ...            0        1         0   
1               0                  0  ...            1        0         1   
2               0                  0  ...            1        1         0   
3               0                  0  ...            1        0         1   
4               0                  0  ...            1        1         0   
...           ...                ...  ...          ...      ...       ...   
4516            0                  0  ...            1        1         0   
4517            0                  1  ...            1        0         1   
4518            0                  0  ...            0        1         0   
4519            0                  0  ...            0        1         0   
4520            0                  0  ...            1        0         1   

      contact_cellular  contact_telephone  contact_unknown  poutcome_failure  \
0                    1                  0                0                 0   
1                    1                  0                0                 1   
2                    1                  0                0                 1   
3                    0                  0                1                 0   
4                    0                  0                1                 0   
...                ...                ...              ...               ...   
4516                 1                  0                0                 0   
4517                 0                  0                1                 0   
4518                 1                  0                0                 0   
4519                 1                  0                0                 0   
4520                 1                  0                0                 0   

      poutcome_other  poutcome_success  poutcome_unknown  
0                  0                 0                 1  
1                  0                 0                 0  
2                  0                 0                 0  
3                  0                 0                 1  
4                  0                 0                 1  
...              ...    

In [32]:
dummied_data=pd.get_dummies(data[['marital','job','education','default','housing','loan','contact','poutcome']])

In [33]:
data1=data.drop(['marital','job','education','month','default','housing','loan','contact','poutcome'],axis=1)

In [34]:
data1.columns

Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'y'],
      dtype='object')

In [35]:
dataf=data1.merge(dummied_data,left_index=True,right_index=True)

In [36]:
dataf.shape

(4521, 40)

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
x=dataf[['age','balance','day','duration','campaign','pdays','previous',
       'marital_divorced', 'marital_married', 'marital_single',
       'job_admin.', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed', 'job_services',
       'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
       'education_primary', 'education_secondary', 'education_tertiary',
       'education_unknown', 'default_no', 'default_yes', 'housing_no',
       'housing_yes', 'loan_no', 'loan_yes', 'contact_cellular',
       'contact_telephone', 'contact_unknown', 'poutcome_failure',
       'poutcome_other', 'poutcome_success', 'poutcome_unknown']]

In [39]:
y=data['y']

In [40]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2)

In [41]:
from sklearn.linear_model  import LogisticRegression

In [42]:
model=LogisticRegression()

In [43]:
model.fit(train_x,train_y)

C:\Users\Manirathinam\Anaconda3\Anaconda New\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [44]:
y_pred=model.predict(test_x)

In [45]:
result=pd.DataFrame({'actual':test_y,'predicted':y_pred})

In [46]:
result

actual predicted
132      no        no
2289     no        no
3057     no        no
2445     no        no
80      yes        no
...     ...       ...
700      no        no
3781     no        no
1368     no        no
1967     no        no
2241     no        no

[905 rows x 2 columns]

In [47]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [48]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [49]:
print((799/(799+56)))
print((33/(33+17)))

(.93+.66)/2

0.9345029239766082
0.66


0.795

In [50]:
print(accuracy_score(test_y,y_pred))
print(confusion_matrix(test_y,y_pred))

0.8994475138121547
[[786  15]
 [ 76  28]]


In [51]:
print(precision_score(test_y_new,y_pred_new))
print(recall_score(test_y_new,y_pred_new))
print(f1_score(test_y_new,y_pred_new))

NameError: name 'test_y_new' is not defined

In [52]:
type(test_y)

pandas.core.series.Series

In [53]:
type(y_pred)

numpy.ndarray

In [54]:
test_y_new = test_y.map(lambda x: 1 if x == "yes" else 0)

In [55]:
test_y_new.head()

132     0
2289    0
3057    0
2445    0
80      1
Name: y, dtype: int64

In [56]:
y_pred_new = pd.Series(y_pred).map(lambda x: 1 if x == "yes" else 0)